/* ------------------------------------------------------------
   PRODUCTS — the catalogue. Edit this file to add, remove or
   change products; nothing in index.html needs to change.
   Add `img:"images/kundan-rani-haar.jpg"` to any item and the
   photo replaces the placeholder automatically. Or use `gallery`
   with an array of image paths for multiple photos.
   ------------------------------------------------------------ */
const PRODUCTS = [
 {id:"nz-101", name:"Kundan Rani Haar Set",        line:"ethnic",  type:"necklace-set", price:3450, mrp:4600, occ:["bridal","festive"], badge:"bestseller", stones:"Uncut kundan with pearl drops", plating:"22k gold tone on brass", incl:"Long haar, short necklace, jhumkas, maang tikka", size:"Haar 42 cm · choker 36 cm, adjustable dori", weight:"185 g"},
 {id:"nz-102", name:"Meenakari Peacock Jhumkas",   line:"ethnic",  type:"earrings",     price:890,  mrp:1200, occ:["festive","party"],  badge:"",           stones:"Enamel meena with kundan centre", plating:"Antique gold tone", incl:"Pair of jhumkas with saharas", size:"5.4 cm drop", weight:"32 g"},
 {id:"nz-103", name:"Temple Lakshmi Choker Set",   line:"ethnic",  type:"necklace-set", price:2650, mrp:3400, occ:["bridal","festive"], badge:"",           stones:"Ruby and green synthetic stones", plating:"Matte antique gold", incl:"Choker and matching jhumkas", size:"Choker 34 cm, adjustable", weight:"142 g"},
 {id:"nz-104", name:"Polki Maang Tikka",           line:"ethnic",  type:"maang-tikka",  price:640,  mrp:850,  occ:["bridal","festive"], badge:"new",        stones:"Polki-look stones, pearl edge", plating:"Antique gold tone", incl:"Single tikka with hair hook", size:"6 cm chain drop", weight:"18 g"},
 {id:"nz-105", name:"Antique Gold Kada Pair",      line:"ethnic",  type:"kada",         price:1180, mrp:1500, occ:["festive"],          badge:"",           stones:"Textured, stoneless", plating:"Antique gold tone on brass", incl:"Pair of openable kadas", size:"2.4 / 2.6 available", weight:"96 g pair"},
 {id:"nz-106", name:"Meenakari Chandbali",         line:"ethnic",  type:"earrings",     price:760,  mrp:0,    occ:["festive","party"],  badge:"",           stones:"Meena work, pearl fringe", plating:"Gold tone", incl:"Pair with push-back", size:"4.8 cm drop", weight:"27 g"},
 {id:"nz-107", name:"Ethnic Jhumka",         line:"ethnic",  type:"earrings",     price:1000,  mrp:0,    occ:["festive","party"],  badge:"",           stones:"Kundan Work, pearl fringe", plating:"Gold tone", incl:"Pair with push-back", size:"7.5 cm drop", weight:"27 g",gallery:["images/nz-107-jhumka-1.jpg","images/nz-107-jhumka-2.jpg","images/nz-107-jhumka-3.jpg","images/nz-107-jhumka-4.jpg","images/nz-107-jhumka-5.jpg","images/nz-107-jhumka-6.jpg"]},
 {id:"nz-201", name:"AD Solitaire Necklace Set",   line:"ad",      type:"necklace-set", price:2990, mrp:3900, occ:["bridal","party"],   badge:"bestseller", stones:"AAA cubic zirconia, prong set", plating:"Rhodium (silver tone)", incl:"Necklace and matching studs", size:"38 cm, 5 cm extender", weight:"78 g"},
 {id:"nz-202", name:"AD Chandelier Drops",         line:"ad",      type:"earrings",     price:1150, mrp:1500, occ:["party","bridal"],   badge:"",           stones:"Round and marquise CZ", plating:"Rhodium", incl:"Pair with screw-back", size:"6.1 cm drop", weight:"24 g"},
 {id:"nz-203", name:"AD Tennis Bracelet",          line:"ad",      type:"bracelets",    price:1390, mrp:0,    occ:["party","office"],   badge:"new",        stones:"3 mm CZ line setting", plating:"Rhodium", incl:"Single bracelet, box clasp", size:"18 cm with safety catch", weight:"21 g"},
 {id:"nz-204", name:"AD Halo Ring",                line:"ad",      type:"rings",        price:520,  mrp:700,  occ:["everyday","party"], badge:"",           stones:"6 mm centre CZ with halo", plating:"Rhodium", incl:"Single ring", size:"Sizes 12 – 18", weight:"6 g"},
 {id:"nz-205", name:"Sapphire Blue AD Choker Set", line:"ad",      type:"necklace-set", price:3290, mrp:4200, occ:["party","bridal"],   badge:"",           stones:"Blue CZ centres, white CZ pave", plating:"Rhodium", incl:"Choker and drop earrings", size:"35 cm, adjustable chain", weight:"88 g"},
 {id:"nz-206", name:"AD Stud Trio Box",            line:"ad",      type:"earrings",     price:690,  mrp:900,  occ:["everyday","office"],badge:"bestseller", stones:"4 / 6 / 8 mm CZ solitaires", plating:"Rhodium", incl:"Three pairs in one box", size:"Three sizes", weight:"14 g total"},

 {id:"nz-301", name:"Brushed Gold Hoops",          line:"western", type:"earrings",     price:450,  mrp:0,    occ:["everyday","office"],badge:"bestseller", stones:"None — brushed metal finish", plating:"18k gold tone, e-coated", incl:"Pair of hoops", size:"32 mm diameter", weight:"9 g"},
 {id:"nz-302", name:"Pearl Drop Y-Necklace",       line:"western", type:"necklace",     price:980,  mrp:1300, occ:["party","office"],   badge:"",           stones:"Shell pearl drop", plating:"Gold tone chain", incl:"Single necklace", size:"44 cm with 8 cm drop", weight:"18 g"},
 {id:"nz-303", name:"Stacked Bangle Trio",         line:"western", type:"bangles",      price:740,  mrp:950,  occ:["office","everyday"],badge:"",           stones:"None", plating:"Gold tone, two-finish", incl:"Set of three thin bangles", size:"2.4 / 2.6", weight:"34 g set"},
 {id:"nz-304", name:"Emerald Cocktail Ring",       line:"western", type:"rings",        price:860,  mrp:1100, occ:["party"],            badge:"new",        stones:"Synthetic emerald with CZ shoulder", plating:"Gold tone", incl:"Single statement ring", size:"Sizes 12 – 18", weight:"11 g"},
 {id:"nz-305", name:"Minimal Bar Pendant",         line:"western", type:"necklace",     price:390,  mrp:0,    occ:["everyday","office"],badge:"",           stones:"None", plating:"Gold tone, e-coated", incl:"Pendant with 42 cm chain", size:"25 mm bar", weight:"7 g"},
 {id:"nz-306", name:"Chain-Link Anklet",           line:"western", type:"anklets",      price:420,  mrp:560,  occ:["everyday"],         badge:"",           stones:"None", plating:"Silver tone, anti-tarnish coat", incl:"Single anklet", size:"25 cm with extender", weight:"8 g"},
 {id:"nz-108", name:"White Meenakari Cutwork Bangles", line:"ethnic", type:"bangles", price:4000, mrp:4500, occ:["festive","party"], badge:"", stones:"White enamel oval panel with gold floral cutwork medallion", plating:"Gold tone on brass, multi-row band", incl:"Pair of bangles", size:"(est.) 2.4 / 2.6 diameter — opening mechanism not visible in photo, confirm", weight:"40 g",gallery:["images/nz-108-bangle-1.jpg"]},
 {id:"nz-307", name:"Multi-Tone Ribbed Bangle Stack", line:"western", type:"bangles", price:3500, mrp:5000, occ:["everyday","office"], badge:"", stones:"None — ribbed/textured metal finish", plating:"Multi-tone gold-edged finish: gunmetal black, rose gold, gold tone, rhodium silver", incl:"Set of 4 stackable bangles, one bangle per tone", size:"(est.) 2.4 in / 6 cm diameter", weight:"40 g",gallery:["images/nz-307-bangle-2.jpg"]},
 {id:"nz-000001", name:"Mint Kundan Chandbali", line:"ethnic", type:"earrings", price:1500, mrp:1800, occ:["festive","party"], badge:"new", stones:"Clear kundan solitaire top, mint green cabochons with green meena floral work, kundan halo and seed pearl border", plating:"Gold tone on brass", incl:"Pair with push-back", size:"7.5 cm drop · 2.5 cm wide", weight:"20 g", gallery:["images/nz-000001-chandbali-1.jpg","images/nz-000001-chandbali-2.jpg","images/nz-000001-chandbali-3.jpg","images/nz-000001-chandbali-4.jpg","images/nz-000001-chandbali-5.jpg"]},
 {id:"nz-000002", name:"Mint Kundan Chandbali", line:"ethnic", type:"earrings", price:2000, mrp:2200, occ:["festive","party"], badge:"bestseller", stones:"Clear kundan solitaire top, mint green cabochons with green meena floral work, kundan halo and seed pearl border", plating:"Gold tone on brass", incl:"Pair with push-back", size:"7.5 cm drop · 2.5 cm wide", weight:"25 g", gallery:["images/nz-000002-chandbali-1.jpg","images/nz-000002-chandbali-2.jpg","images/nz-000002-chandbali-3.jpg","images/nz-000002-chandbali-4.jpg","images/nz-000002-chandbali-5.jpg"]}
];
